### ISSUE TITLE
[Idea] Add the content of the bagpacks in the inventory

### ISSUE THREAD

**Issue by doej1367** [LeaPhant/skyblock-stats#10]
Not really something important for the early development, 
but maybe add some feature one day that makes it possible to look into backpacks.
Amaizing work with the new inventory viewer btw :)
![grafik](https://user-images.githubusercontent.com/19228364/67876661-8800b980-fb38-11e9-8cfa-103102d274a4.png)

**Comment by ShaunMack** [comment]
It appears that this has been added. From what I can tell it works properly, however there is no enchanted overlay for items in the pack when hovering.

As an example, hover over the backpack in my inventory that contains enchanted ender pearls. They currently look like normal ender pearls.

**Comment by LeaPhant** [comment]
I didn't add that for performance reasons, but I guess I can add a static overlay. Also I totally forgot about this issue, I'll close it after adding the enchanted overlay.
