### ISSUE TITLE
Enchanted Item Overlay

### ISSUE THREAD

**Issue by FlexXx1212** [LeaPhant/skyblock-stats#11]
Hey, awesome work, i was actually thinking about doing the same, but a few days later you already did it :)

It would be nice to have any indicator, besides hovering over the item itself, that it is an enchanted item instead of a normal one. (like down below)

For an easy workaround (instead of implementing a real enchanted look) you could also just indicate it with some shiny/purple boarder or something.

![image](https://user-images.githubusercontent.com/33630274/67881848-8d163680-fb41-11e9-95fd-67cb1827dcdd.png)

(ps: i may also contribute to this project when i got some time on my hands)

**Comment by LeaPhant** [comment]
I tried a lot of different ways over the past days with most of them having performance issues and settled on a canvas solution now (animated on desktop, static on mobile). I will still try to optimize it further but enchanted items are now distinguishable, although custom heads and gif items don't work (yet?).

**Comment by ShaunMack** [comment]
Looking pretty good, however not every item is properly highlighted; In particular, Hot Potato Books are not shown enchanted. For reference, check the ender chest of https://sky.lea.moe/stats/LonelyFatKid/Zucchini

**Comment by LeaPhant** [comment]
Oh, thanks for the hint! By comparing that to other items I think I've finally found a way of reliably checking whether an item is enchanted. If there's any items that are still off please report back.

**Comment by ShaunMack** [comment]
Looks great! I haven't found any other items that appear incorrectly so far.

**Comment by LeaPhant** [comment]
Yeah, potions are still static because I haven't gotten around getting clean icons for them since I used a mod to get all the icon items in high quality which captures the enchantment overlay. Will fix that some other time™.
