### ISSUE TITLE
[Idea] Add Collection Stats

### ISSUE THREAD

**Issue by DJtheRedstoner** [LeaPhant/skyblock-stats#15]
The API has the collection stats and I think it would be cool the see these online especially for making form signatures (when that gets added) this way players could see what recipes you have unlocked.

**Comment by ShaunMack** [comment]
Definitely a great idea. +1

**Comment by doej1367** [comment]
If you are looking for a list of all the unlockable recipes this might help 
(It might not be perfect, but it is something)
https://hypixel.net/threads/spreadsheet-recepie-search-function.2316070/

**Comment by DJtheRedstoner** [comment]
> If you are looking for a list of all the unlockable recipes this may help, so you don't have to write everything from scratch, depending on how you decide to implement that thought. (It might not be perfect, but it is something)
https://hypixel.net/threads/spreadsheet-recepie-search-function.2316070/

Thank you but there is actually an API resources endpoint with all the collection rewards/recipes. 
https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/methods/resources.md

**Comment by DaWenning** [comment]
If you need the Item Amount required for each level I got you covered. 

https://recklessGreed.de/hypixel/itemAmounts

**Comment by LeaPhant** [comment]
@DaWenning But that data is already available from the official api. 🤔

**Comment by DaWenning** [comment]
It is o.o 
Well then I did some extra work I guess. Did not find it and copied every level from Minecraft.

**Comment by LeaPhant** [comment]
Don't worry I did the same for the skill levels because I didn't know the endpoint existed. :)
