### ISSUE TITLE
[Bug] Api doesn't show speed properly

### ISSUE THREAD

**Issue by questionableintellect** [LeaPhant/skyblock-stats#16]
I have 104 speed, due to my having a speed talisman and two reforges that raise my speed by one. The api shows my speed as two. It's not much of a problem, but if you could fix, that would be great.

**Comment by LeaPhant** [comment]
Could you tell me your Minecraft username so I can check?

**Comment by questionableintellect** [comment]
My username is 100_acorn_squash

**Comment by LeaPhant** [comment]
Speed Talismans attribute to your stats correctly now with commit https://github.com/LeaPhant/skyblock-stats/commit/be43bbf384e0f286364a548820b82abc7d9e2344.

Thanks a lot for your bug report!
