### ISSUE TITLE
The health

### ISSUE THREAD

**Issue by dusty1010** [LeaPhant/skyblock-stats#20]
the health is broken. it says that 512 health for a person that only has 112 health can any fix it. I'm new

**Comment by LeaPhant** [comment]
Could you please tell me their Minecraft username so I can check?

**Comment by ShaunMack** [comment]
Unable to reproduce issue looking at many different profiles. @dusty1010 if you have any information to share, you should do so ASAP.

**Comment by builder-247** [comment]
My theory is they checked the wrong profile.

**Comment by DJtheRedstoner** [comment]
They may also have been looking at effective HP not normal HP.

**Comment by LeaPhant** [comment]
The fairy bonus was maxed out at 0 fairy exchanges, this has been fixed in https://github.com/LeaPhant/skyblock-stats/commit/6eae383811cb6c963db5465a71e6eaf4bd809881.
