### ISSUE TITLE
[Idea] Add support for UUIDs

### ISSUE THREAD

**Issue by DJtheRedstoner** [LeaPhant/skyblock-stats#25]
I think it would be nice to have support for UUIDs, especially if Mojang's servers are down or theres is some other issue. Also having support for Hypixel profile ids (maybe not from the main page but just using the url) would be nice.

**Comment by LeaPhant** [comment]
Definitely, there's multiple bugs that can occur with just using usernames and profile names. If a co-op partner on your island hasn't logged in on Hypixel after changing their Minecraft name it will just say player not found. Also sometimes profile names can be different per player if they join a co-op and already have a profile with that name themselves. It's really messy atm.

I'll probably add linking support via IDs (for both username and profile) and rewrite the URL to a readable one on page load.

**Comment by LeaPhant** [comment]
Finally implemented this! https://github.com/LeaPhant/skyblock-stats/commit/8bef57ad25e6dfadcc424611bd34728bef95090c

With this change you will now also be able to view profiles of co-op members who have left.
