### ISSUE TITLE
Unconfirmed Coop Invitations cause chaos

### ISSUE THREAD

**Issue by Donald-Tho** [LeaPhant/skyblock-stats#28]
When you go to https://sky.lea.moe/stats/Kefir101Awesome/Apple
it is an example of this. I only noticed this because it was causing problems in my own application for creating a guild slayer xp leaderboard. Maybe check to see if the profile is actually an unaccepted coop invite before adding it to the list and processing it.

**Comment by LeaPhant** [comment]
Unfortunately I'd have to send a request for each profile for that, I did add some checks for a somewhat clearer error message though. Fixing this is on Hypixel.

Thanks for reporting though!
