### ISSUE TITLE
Redirecting Names

### ISSUE THREAD

**Issue by EkeeIsBae** [LeaPhant/skyblock-stats#30]
I just noticed that some names redirect you to other names. When I was trying to look at my profile today I had noticed that when I typed in "stats/ekee" it would redirect me to someone named "Beebeekee". The only way I can get the site to not redirect me is by using my uuid instead. I tested this out with other names that I knew were real; like "nvit" "15h" and names with higher than 4 characters. 

It seems like names with 4 or fewer letters get swapped for a larger name that includes the original name. With some exceptions with names that have numbers and letters in them (15h). At least that's what I found.

**Comment by LeaPhant** [comment]
Oops, this was a horrible oversight on my end, I forgot specifying to only match the full string in my DB query. It's fixed now.

Thank you for reporting!
