### ISSUE TITLE
Enchanted Items displayed as a White box instead of the item

### ISSUE THREAD

**Issue by xNaCly** [LeaPhant/skyblock-stats#34]
firefox 74.0
![Capture](https://user-images.githubusercontent.com/47723417/76698769-ae199700-669e-11ea-9575-38929d9a6971.PNG)

**Comment by evanmn** [comment]
I'm unable to replicate this. Could you provide the player/item where you see this, and your [about:support](about:support) from Firefox?

**Comment by xNaCly** [comment]
about:support:  https://pastebin.com/WUzE41Vg
player: xnacly
all enchanted items in his inv
