### ISSUE TITLE
wolf slayer level bug

### ISSUE THREAD

**Issue by WahlMandat** [LeaPhant/skyblock-stats#35]
The wolf slayer level is wrong displayed, I have 480k xp and it still shows level 7 but I'm level 8.
source: https://sky.lea.moe/stats/Tobii/Mango
img: https://prnt.sc/rkc6hb
Hopefully I can help you with this :)

**Comment by LeaPhant** [comment]
Are you sure you've claimed your Wolf Slayer 8 level rewards ingame?

**Comment by WahlMandat** [comment]
Yea that was the problem.
Thank you very much.
