### ISSUE TITLE
[Bug] Searching my username displays the profile of another user with a similar username

### ISSUE THREAD

**Issue by RefractionDev** [LeaPhant/skyblock-stats#37]
Since yesterday, searching my name on your site will result in the profile of a user with a name similar to mine (Refraction -> Refractioning).

Strangely, entering the URL to my stats directly - https://sky.lea.moe/stats/Refraction/Apple - still results in this other user's profile appearing. I checked their NameMC profile to see if they had recently changed their username causing this bug, but it's been "Refractioning" for 2 years now.

The only way I can view my stats is by searching up my co-op members and selecting myself from the drop down list.

**Comment by LeaPhant** [comment]
Sorry for that, I optimized the DB queries too much again... fixed in https://github.com/LeaPhant/skyblock-stats/commit/0ba02f070f2b886d481c8fea59a7d8798e9fa187.

Thanks for reporting!
