### ISSUE TITLE
Skin preview has incorrect pixel

### ISSUE THREAD

**Issue by SirNapkin1334** [LeaPhant/skyblock-stats#38]
Hello, there's a strange bug with my profile. One of the pixels on my head is incorrect. On the side of my head, there's single red pixel, which is not on my skin. I don't know why this happens, but it's not correct.
https://sky.lea.moe/stats/SirNapkin1334/Cucumber

What it looks like:
![image](https://user-images.githubusercontent.com/31591796/78828736-02f8b680-799a-11ea-9f64-f1f3a7e861bd.png)

What it should look like:
![image](https://user-images.githubusercontent.com/31591796/78828771-1277ff80-799a-11ea-93ab-1b556a8d9920.png)

My skin file for reference:
![tux](https://user-images.githubusercontent.com/31591796/78828828-2a4f8380-799a-11ea-908f-be8265bdac0a.png)

**Comment by LeaPhant** [comment]
I'm using a third-party site for those 3D skin renders (https://visage.surgeplay.com) and the project is archived so I doubt it'll get fixed on their end. :/

I'll keep this issue open in case I decide to host my own instance and fix it.

**Comment by Nisutec** [comment]
Try this 3D skin render SIte (https://crafatar.com/)

**Comment by SirNapkin1334** [comment]
Yes but that site does not show the second layer of the skin. Perhaps we could see what namemc uses?

**Comment by Nisutec** [comment]
It supports the second layer of the skin. 
![Options](https://p52.p0.n0.cdn.getcloudapp.com/items/9ZuEexoA/Image%202020-04-10%20at%208.13.36%20PM.png?v=f816552f58de6a27aaca4104411cf0ab)

**Comment by SirNapkin1334** [comment]
Oh.

**Comment by Nisutec** [comment]
And  @SirNapkin1334 NameMC uses also Crafatar 🙂

**Comment by LeaPhant** [comment]
I'm not a fan of the flat isometric renders from Crafatar so I'm keeping this for now even if there might be bugs. It would be a lot less visually pleasing if the player skin on the left didn't blend in with the background like it does now.

**Comment by Nisutec** [comment]
Than look at this (https://minerender.org/#skins) it uses crafatar to generate dynamic 3D renders.

**Comment by LeaPhant** [comment]
I know that project but the site is already pretty resource heavy I think a client-side 3d renderer would be a bad idea.

**Comment by LeaPhant** [comment]
Fixed with new skin viewer.
