### ISSUE TITLE
Perfect Armor Texture

### ISSUE THREAD

**Issue by Nisutec** [LeaPhant/skyblock-stats#39]
Hallo,
Is it possible to change the Perfect Armor Textures to this Texture Pack (https://hypixel.net/threads/hypixel-skyblock-pack-winter-update.2103515/). At the moment the Vanilla+ SkyBlock Pack has not a armor Texture for all tiers of the armor.

![Perfect Armor](https://p52.p0.n0.cdn.getcloudapp.com/items/YEu1GjJy/pa.png?v=b69f92f092a3b6853e8cf2533ad4a6cf)

**Comment by LeaPhant** [comment]
This comes down to preference, there'll be a pack selector eventually which will also include the Hypixel SkyBlock Pack. Then you can decide for yourself which textures to use.
