### ISSUE TITLE
[Suggestion] Add Accessories from the Inventory

### ISSUE THREAD

**Issue by doej1367** [LeaPhant/skyblock-stats#4]
Just noticed that it seems you've forgotten about / not implemented yet that you can put accessories in the inventory and they still work. You might wanna add those one way or the other.

**Comment by LeaPhant** [comment]
Are you sure? It's implemented and I just tried it and have it working. Your profile might have just not updated yet when you checked.

**Comment by ShaunMack** [comment]
I can confirm that accessories in the inventory are listed properly.

**Comment by LeaPhant** [comment]
I'll close this then.
