### ISSUE TITLE
Skin not loading

### ISSUE THREAD

**Issue by StopTakingLs** [LeaPhant/skyblock-stats#43]
I have had an issue when looking my name up on skylea it has been showing steve skin even though it is not that in game. Any idea how this can be fixed
sorry if this was a waste for you :)
![bug](https://user-images.githubusercontent.com/64437941/80414394-d42d7c00-8885-11ea-8156-017a69bc68d1.PNG)

**Comment by LeaPhant** [comment]
Was due to Mojang API, closing this.
