### ISSUE TITLE
Pet Luck not included on profile

### ISSUE THREAD

**Issue by hartman-devs** [LeaPhant/skyblock-stats#47]
Most things appear correctly, but base pet luck isn't loading correctly for all players. I'm not sure if it's a numbers thing (e.g. pet luck doesn't load for players with <10) or if it's an API thing.

**Comment by LeaPhant** [comment]
Probably because their Skills API is disabled.

**Comment by hartman-devs** [comment]
Right - I know if I look my own profile up, it shows 0 pet luck. My Skills API is disabled (currently), but my other skills show because of achievements. My friend is offline, but I'll ask them to check later if needed.

I know the text underneath mentions that if the Skills API access is disabled, skill information will be pulled from player achievements. However, I think for the average player, "achievements" means something different than it does in regards to information the API can pull - since individual leveling messages might be seen as achievements. It might be useful to revise the warning message to "Skills shown are retrieved from Global/Hypixel Achievements. Enable Skills API for more accurate data." if the user doesn't have the API enabled.

**Comment by LeaPhant** [comment]
The thing is just they either forgot adding achievements for the Taming skill or didn't want to add any. I'm still hoping for them to be added eventually, for now it doesn't really matter too much. I think the warning text is fine as-is and I don't wanna make it longer cause then a linebreak would happen, it's already pretty clear you just gotta live with inaccurate data if the API is disabled.

**Comment by hartman-devs** [comment]
Makes sense, on your end - line breaks are definitely not fun to design with. Just thought I'd look into why and offer the suggestion!
