### ISSUE TITLE
Bug about usernames

### ISSUE THREAD

**Issue by PlanetXtreme** [LeaPhant/skyblock-stats#5]
Not sure if this is intentional, but A user by the name of Sakies hasn't joined skyblock for about 2 months now, and when I search her name on https://plancke.io/hypixel/player/stats/sakies it comes up, but when I click the button named "SkyBlock Stats" no stats come up and it says "error, Player has no SkyBlock profiles."
Pretty sure it's because she hasn't been online but just letting you know.

**Comment by LeaPhant** [comment]
Unfortunately the API returns no SkyBlock profiles for her and a profile with her uuid doesn't exist either.

This is probably based on https://github.com/HypixelDev/PublicAPI/issues/136 and there's not much I can do.

Plancke is unrelated to my website and shows a "SkyBlock Stats" button for every player regardless of whether they played it.
