### ISSUE TITLE
Fishing sea creature chance

### ISSUE THREAD

**Issue by LordBugfisch** [LeaPhant/skyblock-stats#50]
Hey :)

I have noticed, that some factors count towards the fishing scg chance on ur website and some not. I think the ability and passive of the Dolphin pet are missing out. Its not criticism, just wanted to let you know to improve your website we all love. c:
Maybe you could add there too, that 41% is the capped scg chance. 
Hope i could help

Buggi

**Comment by LeaPhant** [comment]
Hi!

Pet abilities aren't accounted for cause they're not returned by the API. I haven't had the motivation to input them all manually yet but I might eventually.

Sea Creature Chance being capped at 41% is a myth caused by a misleading patch note, there is no cap. xd

**Comment by LordBugfisch** [comment]
Hi again

i just heard that with the 41% cap and saw the fact on the Hypixel Skyblock Fandom tho i thought it was true. :o
