### ISSUE TITLE
Twitch and Twitter links do not work properly

### ISSUE THREAD

**Issue by iwillreku3206** [LeaPhant/skyblock-stats#53]
Social media links (see below image) are linked as `<a href="twitter.com/TWITTERUSERNAME></a>"` which causes it to to go to `https://sky.lea.moe/stats/USERNAME/twitter/TWITTERUSERNAME` instead of `https://twitter.com/TWITTERUSERNAME`. As far as I can tell, this does not affect YT and Hypixel Forum, but does affect Twitch.

This may be fixed by adding `https://` or `http://` to the beginning of the URL.

![sky lea moe bug (social links)](https://user-images.githubusercontent.com/37181282/84644139-560a5f00-af31-11ea-9d3e-5b6631eb25c3.png)

**Comment by samm4x** [comment]
All of the social media links work perfectly on my page: 
https://sky.lea.moe/stats/samm4x/Coconut

It may be beacuse when you entered your socials to Hypixel, yo

**Comment by iwillreku3206** [comment]
I only added 'twitter.com'

**Comment by samm4x** [comment]
That's the problem then. The Hypixel API doesn't add "https://" for you, as you are meant to input it yourself at the start of the link. :)
