### ISSUE TITLE
The website thinks im wiped.

### ISSUE THREAD

**Issue by AnkozOOGABOOGA** [LeaPhant/skyblock-stats#58]
One of the profiles I was apart of got wiped and now I cant use sky lea to access my skyblock stats. Hypixel's API is not the issues because discord bots can still check my API.

If necessary my IGN is Ankoz.

**Comment by LeaPhant** [comment]
Fixed in https://github.com/LeaPhant/skyblock-stats/commit/9efff2175636e0a25f0724f7e5b06f8110a4e8d8.
