### ISSUE TITLE
Ender Chest Slots

### ISSUE THREAD

**Issue by MBacon15** [LeaPhant/skyblock-stats#6]
Obsidian Collection expands the size of your personal enderchest and the site doesn't seem to reflect that correctly.

**Comment by LeaPhant** [comment]
I checked a profile with a fully expanded enderchest and it seems to work just fine.

![image](https://user-images.githubusercontent.com/14080165/67807555-4b2fb680-fa95-11e9-8391-72b184058470.png)

The slots might not show up if there's nothing in them. The API doesn't return the chest size, only a fixed amount of slots which I use.

**Comment by LeaPhant** [comment]
Oh, there was however a bug I just noticed that the first row of the enderchest was missing! Maybe this  is what threw you off. I fixed this in https://github.com/LeaPhant/skyblock-stats/commit/1d1517781840e82b0c62a4a97c5b96dbec017936. :smile:
