### ISSUE TITLE
Error on the site.

### ISSUE THREAD

**Issue by UnkillableDebt** [LeaPhant/skyblock-stats#63]
The website said to go onto Firefox or Google Chrome when it was open in both chrome and firefox.
![sky lea moe - Google Chrome 7_15_2020 6_50_24 PM](https://user-images.githubusercontent.com/64228933/87607879-55015480-c6cc-11ea-82db-7b5e2b1d82e4.png)

**Comment by UnkillableDebt** [comment]
The website only has the normal configuration available in incognito mode.

**Comment by WarpWing** [comment]
I ain't no expert but this is probably a client-side issue.  Could you try to do a hard refresh by holding down control and clicking the reload button?
