### ISSUE TITLE
[IDEA] Chicken Racing Stat in Races Section

### ISSUE THREAD

**Issue by Vyke-Ajemian** [LeaPhant/skyblock-stats#66]
Hey.

Is it possible for there to be a stat for your Chicken Racing record and at what checkpoint you're at?

It can be added in the Races tab, along with the two other ones.

Thanks.

**Comment by metalcupcake5** [comment]
I've looked through the api and there doesn't seem to be anything for the chicken race. Feel free to look yourself and comment back if you find it.

**Comment by LeaPhant** [comment]
The time should be there automatically if you have completed it, the API doesn't return any partial progress for this race.
