### ISSUE TITLE
Rarity Wrong 

### ISSUE THREAD

**Issue by Mytox606** [LeaPhant/skyblock-stats#69]
If you have chosen an other language then english on hypixel, the rarity of an armor, weapons and accesories will be gray, expect for uncommon and mythic items and pets( not transliated if you use german or other language that is not english),

**Comment by LeaPhant** [comment]
I opened an issue on the Hypixel API issue tracker, I'm gonna wait for them to change the API's behavior since it would require many ugly workarounds to support localized NBT.

https://github.com/HypixelDev/PublicAPI/issues/290

**Comment by LeaPhant** [comment]
Added a small workaround in https://github.com/LeaPhant/skyblock-stats/commit/a12c4fabd46c56a9d0c873e017f7727d5146c591 for rarity colors, still hoping for the issue to be resolved on Hypixel's side so other stuff will work correctly again as well.
