### ISSUE TITLE
Speed is miscounted from accessories

### ISSUE THREAD

**Issue by questionableintellect** [LeaPhant/skyblock-stats#76]
I have a speed ring (+3), a frozen chicken (+1), and a potato talisman (+1), but the speed granted from accessories is only +4. None of my accessories reduce speed. Profile is https://sky.lea.moe/stats/100_Acorn_squash/Raspberry . Thanks for the website!

**Comment by builder-247** [comment]
Looks like the code for adding frozen chicken speed is missing, I can add it in a moment.
